import { createContext, useContext, useEffect, useState } from 'react';

const translations = {
  ro: {
    title: 'Tablou de bord de producție',
    signOut: 'Deconectare',
    overview: 'Prezentare generală',
    products: 'Produse',
    inventory: 'Componente',
    sales: 'Vânzări',
    clients: 'Clienți',
    audit: 'Istoric',
    users: 'Utilizatori',
    settings: 'Setări',
    language: 'Limbă',
    english: 'English',
    romanian: 'Română',
    switchTo: 'Comută în',

    loading: 'Se încarcă…',
    cancel: 'Anulează',
    confirm: 'Confirmă',
    confirmAction: 'Confirmă acțiunea',

    loginTitle: 'Tablou de bord de producție',
    loginSubtitle: 'Autentifică-te pentru a continua',
    username: 'Nume de utilizator',
    password: 'Parolă',
    enterUsername: 'Introdu numele de utilizator',
    enterPassword: 'Introdu parola',
    signingIn: 'Autentificare…',
    signIn: 'Autentifică-te',
    demoAccounts: 'Conturi demo',
    demoAdmin: 'Admin',
    demoUser: 'Utilizator',

    overviewRevenuePaid: 'Venituri (plătite)',
    overviewPending: 'În așteptare',
    overviewAborted: 'Anulate',
    overviewClients: 'Clienți',
    overviewProducts: 'Produse',
    overviewProductsInStock: 'Produse în stoc',
    overviewStockUnits: 'Unități în stoc',
    overviewPartsAlerts: 'Alarme componente',
    overviewActive: 'active',
    overviewInCatalog: 'în catalog',
    overviewManuallyTracked: 'urmărite manual',
    overviewInInventory: 'în inventar',
    overviewNeedAttention: 'necesită atenție',
    overviewAllPartsSufficient: 'Toate piesele sunt suficient aprovizionate.',
    overviewNoProductsAvailable: 'Nu există produse disponibile încă.',
    overviewLowOutOfStockParts: 'Componente cu stoc scăzut / epuizat',
    overviewProductStock: 'Stoc produse',
    overviewRecentSales: 'Vânzări recente',
    overviewTablePart: 'Componentă',
    salesCountSuffix: 'vânzări',
    invoiceCountSuffix: 'facturi',
    cancelled: 'anulate',
    overviewTableQty: 'Cant.',
    overviewTableStatus: 'Stare',
    overviewTableProduct: 'Produs',
    overviewTableClient: 'Client',
    overviewTableTotal: 'Total',
    overviewTableAvailable: 'Disponibil',

    statusPending: 'În așteptare',
    statusPaid: 'Plătită',
    statusAborted: 'Anulată',
    statusRefunded: 'Rambursată',
    statusPendingOption: 'În așteptare — plata așteptată',
    statusPaidOption: 'Plătită — componentele sunt deduse imediat',
    saleStatusLifecycle: 'Ciclul de viață al vânzării',
    salesRecords: 'Înregistrări vânzări',
    recordSale: 'Înregistrează vânzare',
    saleProduct: 'Produs',
    saleClient: 'Client',
    saleQty: 'Cant.',
    salePrice: 'Preț unitar',
    saleTotal: 'Total',
    saleStatusField: 'Stare inițială',
    saleInfoPaid: 'Componentele sunt deduse doar când starea este Plătită.',
    saleLockedCannotChange: 'Această vânzare este blocată și nu poate fi modificată.',
    markAsPaid: 'Marchează ca Plătită',
    abortSale: 'Anulează vânzarea',
    refundReverse: 'Rambursează / inversează',
    labelPrint: 'Etichetă',
    statusChange: 'Schimbare stare',
    allowPopups: 'Vă rugăm să permiteți pop-up-urile pentru a deschide eticheta',
    deleteSaleQuestion: 'Șterge vânzarea #{{id}}?',
    or: 'sau',
    stockRestoredOnRefund: 'stoc restaurat la rambursare',
    date: 'Dată',
    by: 'De către',
    saveSale: 'Salvează vânzare',
    updateSaleTitle: 'Actualizează vânzarea #{{id}}',
    chooseNewStatus: 'Alege stare nouă:',
    noStockDeductedSaleCancelled: 'Nu se deduce stoc — vânzare anulată',
    partsRestoredOnRefund: 'Componentele vor fi restaurate în stoc',

    clientsTitle: 'Clienți',
    addClient: 'Adaugă client',
    productsBought: 'Produse cumpărate',
    totalPaid: 'Total (plătit)',
    noneYet: 'Niciunul încă',
    purchaseHistory: 'Istoric cumpărături',
    noPurchasesYet: 'Nicio achiziție încă.',
    totalSpentPaidOnly: 'Total cheltuit (doar plătite)',
    close: 'Închide',
    editClient: 'Editează client',
    addClientTitle: 'Adaugă client',
    editClientTitle: 'Editează client',
    clientEmail: 'Email',
    clientPhone: 'Telefon',
    clientPostcode: 'Cod poștal',
    clientAddress: 'Adresă',
    name: 'Nume',
    company: 'Companie',
    fullnameExample: 'Jane Doe',
    companyExample: 'Acme Ltd',
    phoneExample: '+40 700 000 000',
    postcodeExample: '12345',
    addressExample: 'Stradă, oraș, țară',
    deleteClientQuestion: 'Șterge clientul "{{name}}"?',

    settingsSenderCompanyInfo: 'Expeditor / informații companie',
    settingsInfoDescription: 'Aceste informații apar ca adresa DE PE pe fiecare etichetă de expediere pe care o tipăriți.',
    shippingLabelPreview: 'Previzualizare etichetă de livrare',
    shippingLabelHeading: 'ETICHETĂ DE EXPEDIERE',
    shippingLabelFrom: 'DE LA:',
    shippingLabelTo: 'CĂTRE:',
    shippingLabelProduct: 'PRODUS',
    shippingLabelPreviewNote: 'Previzualizare — eticheta reală este PDF A6',
    saleNumber: 'Vânzare',
    companyName: 'Nume companie',
    companyNameExample: 'My Company SRL',
    streetAddress: 'Adresă stradală',
    streetAddressExample: 'Str. Exemplu 1',
    city: 'Oraș',
    cityExample: 'Cluj-Napoca',
    country: 'Țară',
    countryExample: 'Romania',
    phone: 'Telefon',
    phoneExample: '+40 700 000 000',
    emailLabel: 'Email',
    emailExample: 'contact@mycompany.com',
    savedSuccessfully: 'Salvat cu succes',
    saveSettings: 'Salvează setările',
    saving: 'Se salvează…',
    loginFailed: 'Autentificare eșuată',
    failedLoadSettings: 'Încărcare setări eșuată',
    onlyAdminsCanAddEditDeleteProducts: 'Doar administratorii pot adăuga, edita sau șterge produse.',
    deletePartQuestion: 'Șterge componenta "{{name}}"? Aceasta nu poate fi anulată.',
    deleteProductQuestion: 'Șterge produsul "{{name}}"?',
    previewClientName: 'Nume client',
    previewCompanyName: 'Companie SRL',
    previewAddress: 'Adresă stradală',
    previewCityCountry: 'Oraș, Țară',
    skuLabel: 'SKU',
    qtyLabel: 'Cant.',
    productNamePlaceholder: 'Nume produs aici',

    productsPageTitle: 'Produse',
    addProduct: 'Adaugă produs',
    editProduct: 'Editează produs',
    productName: 'Nume produs',
    productSku: 'SKU / cod',
    salePriceRon: 'Preț de vânzare (RON)',
    stock: 'Stoc',
    description: 'Descriere',
    partsPerUnit: 'Componente per unitate',
    noPartsDefined: 'Nicio componentă definită',
    partsCostPerUnit: 'Costul componentelor per unitate',
    productStock: 'Stoc:',
    addPart: 'Adaugă componentă',
    noPartsAddedYet: 'Nicio componentă adăugată încă.',
    saveProduct: 'Salvează produs',
    billOfMaterials: 'Listă de materiale',
    enterProductName: 'Ex: Placă de control v2',
    enterSku: 'Ex: CB-002',
    enterDescription: 'Descriere scurtă',
    margin: 'Marjă',
    actions: 'Acțiuni',
    time: 'Timp',
    user: 'Utilizator',
    role: 'Rol',
    action: 'Acțiune',
    entity: 'Entitate',
    detail: 'Detaliu',
    lastLogin: 'Ultima autentificare',
    notSpecified: 'Nespecificat',
    enterPartName: 'Ex: Condensator 100µF',
    enterPartSku: 'Ex: CAP-100',

    partsInventory: 'Inventar componente',
    partName: 'Nume componentă',
    partSku: 'SKU',
    qtyInStock: 'Cantitate în stoc',
    minStock: 'Stoc minim',
    unitCostRon: 'Cost unitar (RON)',
    addPartTitle: 'Adaugă componentă',
    editPartTitle: 'Editează componentă',
    onlyAdminsCanManageParts: 'Doar administratorii pot gestiona componentele.',
    addPartButton: 'Adaugă componentă',

    usersManagement: 'Gestionare utilizatori',
    addUser: 'Adaugă utilizator',
    usernameLabel: 'Nume de utilizator',
    fullnameLabel: 'Nume complet',
    passwordLabel: 'Parolă',
    roleLabel: 'Rol',
    removeUser: 'Elimină',
    removeUserQuestion: 'Elimină utilizatorul "{{username}}"?',
    usernameExample: 'ex: jdoe',
    fullnameExample: 'ex: Jane Doe',
    never: 'Niciodată',
    addUserTitle: 'Adaugă utilizator',
    currentUser: 'utilizator curent',
    userRoleAdmin: 'Administrator',
    userRoleUser: 'Utilizator',

    auditLog: 'Istoric audit',
    allActions: 'Toate acțiunile',
    createAction: 'Creare',
    editAction: 'Editare',
    deleteAction: 'Ștergere',
    statusAction: 'Schimbare stare',
    loginAction: 'Autentificare',

    outOfStock: 'Epuizat',
    low: 'Scăzut',
    ok: 'OK',
    productStockOut: 'Epuizat',
    productStockLow: 'Scăzut',
    productStockOk: 'OK',

    add: 'Adaugă',
    save: 'Salvează',
    edit: 'Editează',
    delete: 'Șterge',
    remove: 'Elimină',
    preview: 'Previzualizare',
    loadingMessage: 'Se încarcă…',
    noPurchases: 'Nicio achiziție încă.',
    paymentAwaited: 'Plată în așteptare',
    partsDeductedImmediately: 'Componentele sunt deduse imediat',
    current: 'Activ',
    status: 'Stare',
  },
  en: {
    title: 'Manufacturing Dashboard',
    signOut: 'Sign out',
    overview: 'Overview',
    products: 'Products',
    inventory: 'Parts',
    sales: 'Sales',
    clients: 'Clients',
    audit: 'Audit log',
    users: 'Users',
    settings: 'Settings',
    language: 'Language',
    english: 'English',
    romanian: 'Română',
    switchTo: 'Switch to',

    loading: 'Loading…',
    cancel: 'Cancel',
    confirm: 'Confirm',
    confirmAction: 'Confirm action',

    loginTitle: 'Manufacturing Dashboard',
    loginSubtitle: 'Sign in to continue',
    username: 'Username',
    password: 'Password',
    enterUsername: 'Enter username',
    enterPassword: 'Enter password',
    signingIn: 'Signing in…',
    signIn: 'Sign in',
    demoAccounts: 'Demo accounts',
    demoAdmin: 'Admin',
    demoUser: 'User',

    overviewRevenuePaid: 'Revenue (paid)',
    overviewPending: 'Pending',
    overviewAborted: 'Aborted',
    overviewClients: 'Clients',
    overviewProducts: 'Products',
    overviewProductsInStock: 'Products in stock',
    overviewStockUnits: 'Stock units',
    overviewPartsAlerts: 'Parts alerts',
    overviewActive: 'active',
    overviewInCatalog: 'in catalog',
    overviewManuallyTracked: 'manually tracked',
    overviewInInventory: 'in inventory',
    overviewNeedAttention: 'need attention',
    overviewAllPartsSufficient: 'All parts sufficiently stocked.',
    overviewNoProductsAvailable: 'No products available yet.',
    overviewLowOutOfStockParts: 'Low / out of stock parts',
    overviewProductStock: 'Product stock',
    overviewRecentSales: 'Recent sales',
    overviewTablePart: 'Part',
    salesCountSuffix: 'sales',
    invoiceCountSuffix: 'invoice(s)',
    cancelled: 'cancelled',
    overviewTableQty: 'Qty',
    overviewTableStatus: 'Status',
    overviewTableProduct: 'Product',
    overviewTableClient: 'Client',
    overviewTableTotal: 'Total',
    overviewTableAvailable: 'Available',

    statusPending: 'Pending',
    statusPaid: 'Paid',
    statusAborted: 'Aborted',
    statusRefunded: 'Refunded',
    statusPendingOption: 'Pending — payment awaited',
    statusPaidOption: 'Paid — parts deducted immediately',
    saleStatusLifecycle: 'Sale status lifecycle',
    salesRecords: 'Sales records',
    recordSale: 'Record sale',
    saleProduct: 'Product',
    saleClient: 'Client',
    saleQty: 'Qty',
    salePrice: 'Unit price',
    saleTotal: 'Total',
    saleStatusField: 'Initial status',
    saleInfoPaid: 'Parts are deducted only when status is Paid.',
    saleLockedCannotChange: 'This sale is locked and cannot be changed further.',
    markAsPaid: 'Mark as Paid',
    abortSale: 'Abort sale',
    refundReverse: 'Refund / Reverse',
    labelPrint: 'Label',
    statusChange: 'Status change',
    allowPopups: 'Please allow popups to open the label',
    deleteSaleQuestion: 'Delete sale #{{id}}?',
    or: 'or',
    stockRestoredOnRefund: 'stock restored on Refund',
    date: 'Date',
    by: 'By',
    saveSale: 'Save sale',
    updateSaleTitle: 'Update sale #{{id}}',
    chooseNewStatus: 'Choose new status:',
    noStockDeductedSaleCancelled: 'No stock deducted — sale cancelled',
    partsRestoredOnRefund: 'Parts will be restored to stock',

    clientsTitle: 'Clients',
    addClient: 'Add client',
    productsBought: 'Products bought',
    totalPaid: 'Total (paid)',
    noneYet: 'None yet',
    purchaseHistory: 'Purchase history',
    noPurchasesYet: 'No purchases yet.',
    totalSpentPaidOnly: 'Total spent (paid only)',
    close: 'Close',
    editClient: 'Edit client',
    addClientTitle: 'Add client',
    editClientTitle: 'Edit client',
    clientEmail: 'Email',
    clientPhone: 'Phone',
    clientPostcode: 'Postcode',
    clientAddress: 'Address',
    name: 'Name',
    company: 'Company',
    fullnameExample: 'Jane Doe',
    companyExample: 'Acme Ltd',
    phoneExample: '+40 700 000 000',
    postcodeExample: '12345',
    addressExample: 'Street, city, country',
    deleteClientQuestion: 'Delete client "{{name}}"?',

    settingsSenderCompanyInfo: 'Sender / Company info',
    settingsInfoDescription: 'This information appears as the FROM address on every shipping label you print.',
    shippingLabelPreview: 'Shipping label preview',
    shippingLabelHeading: 'SHIPPING LABEL',
    shippingLabelFrom: 'FROM:',
    shippingLabelTo: 'TO:',
    shippingLabelProduct: 'PRODUCT',
    shippingLabelPreviewNote: 'Preview — actual label is A6 PDF',
    companyName: 'Company name',
    streetAddress: 'Street address',
    city: 'City',
    country: 'Country',
    phone: 'Phone',
    emailLabel: 'Email',
    savedSuccessfully: 'Saved successfully',
    saveSettings: 'Save settings',
    saving: 'Saving…',
    loginFailed: 'Login failed',
    failedLoadSettings: 'Failed to load settings',
    onlyAdminsCanAddEditDeleteProducts: 'Only admins can add, edit, or delete products.',
    deletePartQuestion: 'Delete part "{{name}}"? This cannot be undone.',
    deleteProductQuestion: 'Delete product "{{name}}"?',
    previewClientName: 'Client Name',
    previewCompanyName: 'Company SRL',
    previewAddress: 'Street address',
    previewCityCountry: 'City, Country',

    productsPageTitle: 'Products',
    addProduct: 'Add product',
    editProduct: 'Edit product',
    productName: 'Product name',
    productSku: 'SKU / code',
    salePriceRon: 'Sale price (RON)',
    stock: 'Stock',
    description: 'Description',
    partsPerUnit: 'Parts per unit',
    noPartsDefined: 'No parts defined',
    partsCostPerUnit: 'Parts cost per unit',
    productStock: 'Stock:',
    addPart: 'Add part',
    noPartsAddedYet: 'No parts added yet.',
    saveProduct: 'Save product',
    billOfMaterials: 'Bill of materials',
    enterProductName: 'e.g. Control board v2',
    enterSku: 'e.g. CB-002',
    enterDescription: 'Short description',
    margin: 'Margin',
    actions: 'Actions',
    time: 'Time',
    user: 'User',
    role: 'Role',
    action: 'Action',
    entity: 'Entity',
    detail: 'Detail',
    lastLogin: 'Last login',
    notSpecified: 'Not specified',
    enterPartName: 'e.g. Capacitor 100µF',
    enterPartSku: 'e.g. CAP-100',

    partsInventory: 'Parts inventory',
    partName: 'Part name',
    partSku: 'SKU',
    qtyInStock: 'Qty in stock',
    minStock: 'Min. stock',
    unitCostRon: 'Unit cost (RON)',
    addPartTitle: 'Add part',
    editPartTitle: 'Edit part',
    onlyAdminsCanManageParts: 'Only admins can manage parts.',
    addPartButton: 'Add part',

    usersManagement: 'User management',
    addUser: 'Add user',
    usernameLabel: 'Username',
    fullnameLabel: 'Full name',
    passwordLabel: 'Password',
    roleLabel: 'Role',
    removeUser: 'Remove',
    removeUserQuestion: 'Remove user "{{username}}"?',
    usernameExample: 'e.g. jdoe',
    fullnameExample: 'e.g. Jane Doe',
    never: 'Never',
    addUserTitle: 'Add user',
    currentUser: 'current user',
    userRoleAdmin: 'Admin',
    userRoleUser: 'User',

    auditLog: 'Audit log',
    allActions: 'All actions',
    createAction: 'Create',
    editAction: 'Edit',
    deleteAction: 'Delete',
    statusAction: 'Status change',
    loginAction: 'Login',

    outOfStock: 'Out of stock',
    low: 'Low',
    ok: 'OK',
    productStockOut: 'Out',
    productStockLow: 'Low',
    productStockOk: 'OK',

    add: 'Add',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    remove: 'Remove',
    preview: 'Preview',
    loadingMessage: 'Loading…',
    noPurchases: 'No purchases yet.',
    paymentAwaited: 'Payment awaited',
    partsDeductedImmediately: 'Parts are deducted immediately',
    current: 'Current',
    status: 'Status',
  },
};

const LangCtx = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const stored = window.localStorage.getItem('app-language');
    return stored === 'en' ? 'en' : 'ro';
  });

  useEffect(() => {
    window.localStorage.setItem('app-language', lang);
  }, [lang]);

  function t(key, vars = {}) {
    const text = translations[lang]?.[key] ?? translations.en?.[key] ?? key;
    return Object.keys(vars).reduce((value, name) => value.replaceAll(`{{${name}}}`, vars[name]), text);
  }

  return (
    <LangCtx.Provider value={{ lang, setLang, t }}>
      {children}
    </LangCtx.Provider>
  );
}

export function useLanguage() {
  return useContext(LangCtx);
}
